### ISSUE TITLE
Set up continuous integration testing

### ISSUE THREAD

**Issue by mdpiper** [nhm-usgs/bmi-prms6-surface#16]
We should set up continuous integration testing (e.g., through [Travis CI](https://travis-ci.org/)) to run our unit and integration tests on each push and pull request.

**Comment by rmcd-mscb** [comment]
Mark - I think I've successfully added Travis CI to our nhm-usgs github group

**Comment by mdpiper** [comment]
@rmcd-mscb Awesome! I can look at this with you this afternoon, if you'd like.
