### ISSUE TITLE
PRMS variables can't be accessed with c_loc in surface component BMI

### ISSUE THREAD

**Issue by mdpiper** [nhm-usgs/bmi-prms6-surface#7]
There are several variables used in the surface component BMI that can't be accessed with the `c_loc` function in PRMS. To allow access, either PRMS or the BMI will have to be tweaked.

The first group are type components in PRMS:

1. basin_area_inv
1. last_intcp_stor
1. nlake
1. active_hrus
1. nhru
1. nmonths
1. srunoff_updated_soil

Each of these lacks the `pointer` attribute. For example, here's how `basin_area_inv` is defined in **c_basin.f90**:

    real(r64) :: basin_area_inv

The `pointer` attr is needed for accessing the variable using the `c_loc` function in the BMI. Further, the variables don't have the `allocatable` attr; because many of the type components were set up as allocatable in PRMS, it made it easy to convert them into pointers.

There's a second group of type components, all from the `Control` class:

1. cascade_flag%value
1. dprst_flag%value
1. print_debug%value
1. gsflow_mode

These also lack the `pointer` attribute, so they can't be accessed with `c_loc`.

The last variable is `nowtime`. It also isn't a pointer, and it doesn't have a grid in the BMI.

1. nowtime

**Comment by rmcd-mscb** [comment]
Thanks Mark - here's the pull request https://github.com/nhm-usgs/bmi-prms6-surface/pull/8

**Comment by mdpiper** [comment]
Fixed with #8.
